FROM golang:1.15.6

WORKDIR /go/src/app

COPY . .

# Command below fails
RUN GO111MODULE=auto go get -v -u github.com/go-critic/go-critic/cmd/gocritic

RUN GO111MODULE=on go get -v -u github.com/quasilyte/go-ruleguard/...
RUN go get -v github.com/quasilyte/go-ruleguard/dsl

CMD [ "ruleguard", "-rules", "string-rule.go,worker-rule.go", "."]
