FROM golang:1.15.6

WORKDIR /go/src/app

RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.35.2
#RUN GO111MODULE=on go get -v -u github.com/go-critic/go-critic/cmd/gocritic
RUN go get -v -u github.com/go-critic/go-critic/cmd/gocritic

RUN GO111MODULE=on go get -v -u github.com/quasilyte/go-ruleguard/...
RUN go get -v github.com/quasilyte/go-ruleguard/dsl

COPY . .
CMD [ "ruleguard", "-rules", "rules.go", "."]
