FROM golang:1.15.6

WORKDIR /go/src/app
RUN GO111MODULE=on go get -v github.com/quasilyte/go-ruleguard/...
RUN GO111MODULE=on go get -v github.com/quasilyte/go-ruleguard/dsl

COPY . .
CMD [ "ruleguard", "-rules", "rules.go", "."]
