FROM golang:1.15.6

WORKDIR /go/src/app
RUN GO111MODULE=on go get -v github.com/quasilyte/go-ruleguard@v0.3.0
RUN GO111MODULE=on go get -v github.com/quasilyte/go-ruleguard/cmd/...@v0.3.0
RUN GO111MODULE=on go get -v github.com/quasilyte/go-ruleguard/dsl/...@v0.3.0

COPY . .
CMD [ "ruleguard", "-rules", "rules.go", "."]
