FROM golang:1.15.6

WORKDIR /go/src/github.com/quasilyte
RUN git clone https://github.com/quasilyte/go-ruleguard.git
WORKDIR /go/src/github.com/quasilyte/go-ruleguard
RUN go install -i ./...

WORKDIR /go/src/app

COPY . .
CMD [ "ruleguard", "-rules", "string-rule.go,worker-rule.go", "."]
